directory: /run/media/ok/easystore/Music/
art_filename: albumart
threaded: yes
original_date: no

paths:
  default: $albumartist/$album%aunique{}/$track - $title
  singleton: $albumartist/Unknown Album/$track - $title
  comp: Compilations/$album%aunique{}/$track - $title

plugins:
  - musicbrainz
  - fetchart
  - fromfilename
  - chroma

musicbrainz:
  fetch_pictures: yes
  track_id: yes

lookup:
  auto: yes
  fuzzy: no

chroma:
  auto: yes

scrub:
  auto: yes
  remove_date: yes
  remove: comments

import:
  move: yes
  copy: no
  resume: yes
  write: yes
