directory: /run/media/ok/easystore/Music/
art_filename: albumart

threaded: yes

original_date: no

per_disc_numbering: no



# Plugins to use

plugins:

  - duplicates
  
  - fetchart

  - embedart

  - convert

  - scrub

  - replaygain

  - lastgenre

  - chroma


  - web

  - spotify

  - fromfilename



# Path formatting for filenames

paths:

  default: $albumartist/$album%aunique{}/$track - $title

  singleton: $albumartist/Unknown Album/$track - $title

  comp: Compilations/$album%aunique{}/$track - $title

# Conversion settings

convert:

  auto: no

  ffmpeg: /usr/bin/ffmpeg

  opts: -ab 320k -ac 2 -ar 48000

  max_bitrate: 320

  threads: 1



# Metadata lookup options

lookup:
  auto: yes
  fuzzy: no
#  max_error: 5



# MusicBrainz fetching
paths:
  default: $albumartist/$album%aunique{}/$track - $title
  singleton: $albumartist/Unknown Album/$track - $title
  comp: Compilations/$album%aunique{}/$track - $title

plugins:
  - musicbrainz
  - fetchart
  - fromfilename
  - chroma

import:
  move: yes
  copy: no
  resume: yes
  write: yes
